### ISSUE TITLE
Multiple async pipes should throw

### ISSUE THREAD

**Issue by julien-f** [nodejs/readable-stream#259] opened 2017-02-24 10:42 UTC
AFAIU, it's perfectly valid to pipe multiple times a stream if there are no emitted data between the `pipe()`s.

It's difficult to debug when incorrectly used, I think it would be nice to throw in this case.

**Comment by addaleax** [comment] 2017-02-24 10:47
> It's difficult to debug when incorrectly used, I think it would be nice to throw in this case.

Hm, could you be more more specific when you say “incorrectly used”? How would that look like, for example?

**Comment by julien-f** [comment] 2017-02-24 10:50
Something like that for instance :)

```js
const input = fs.createReadStream('foo.txt')
input.pipe(fs.createWriteStream('bar.txt'))
setTimeout(() => {
  input.pipe(fs.createWriteStream('baz.txt'))
}, 1e3)
```

The workaround would be to create a pass-through stream and pipe the input into it synchronously.

**Comment by mcollina** [comment] 2017-02-24 13:59
@julien-f checking that would be up to you. There are "valid" use cases on tapping into a stream while it's going. Moreover, streams tend to be low-level.

We can discuss on adding some public property to check if the stream is flowing or not.

Check out https://www.npmjs.com/package/cloneable-readable, it might help what you want to achieve.

**Comment by julien-f** [comment] 2017-02-24 16:27
@mcollina I suppose there are valid cases, but they are probably very rare (although we should not break them).

I don't really see the benefit of using `cloneable-reabable`, the clones still have to be created synchronously, just like `passThrough` in my previous example…

**Comment by mcollina** [comment] 2017-02-24 17:06
@julien-f that approach with a `PassThrough` will leak memory.

**Comment by julien-f** [comment] 2017-02-24 17:07
Why is that?

**Comment by calvinmetcalf** [comment] 2017-02-24 17:13
the issue, when you get down to it is that streams, well, stream data and they don't have a mechanism for going backwards or saving what they've already emitted.  E.g. they will by design never save data after you pipe unless you you do it synchronously.

**Comment by julien-f** [comment] 2017-02-24 17:20
That's what I understand, what you mean is that it will take more memory than necessary because every `PassThrough` will keep the data around until consumed?

It would make sense, but it is not a memory leak :p

Node streams are so complicated 😢, impossible to get something right unless you now the underlying implementation :/

**Comment by calvinmetcalf** [comment] 2017-02-24 17:22
@mcollina you sure it will leak data, IIRC it will just stream at the rate of the slowest stream

**Comment by calvinmetcalf** [comment] 2017-02-24 17:23
@julien-f yes streams are really complicated and in all likelihood the only solution is going to be to add more documentation

**Comment by julien-f** [comment] 2017-02-24 17:28
Yes, with use cases :)

- how to pipe to multiple streams
- how to know if the stream is readable if you missed the event

**Comment by calvinmetcalf** [comment] 2017-02-24 17:39
> how to know if the stream is readable if you missed the event

`stream.read()` and seeing if it give you null or data would be how, but that wouldn't tell you if it had emitted data and then became unreadable again.

**Comment by mcollina** [comment] 2017-03-17 10:25
Can we close this?

**Comment by calvinmetcalf** [comment] 2017-03-17 13:38
yes I think so

**Closed** 2017-03-17 13:38 UTC
